export const portfolioData = {
  name: "Deepanshi Ruhil",
  title: "Software Development Engineer",
  tagline: "Building intelligent systems at the intersection of Computer Science and Artificial Intelligence.",
  location: "India",
  email: "deepanshi@example.com",
  github: "github.com/deepanshiruhil",
  linkedin: "linkedin.com/in/deepanshiruhil",

  hero: {
    heading: "Deepanshi Ruhil",
    subheading: "Software Development Engineer",
    description: `Crafting elegant solutions to complex problems. I specialize in building intelligent systems that bridge the gap between research and production — from machine learning pipelines to scalable backend architectures.`,
    specs: [
      { label: "FOCUS", value: "Machine Learning & AI Systems" },
      { label: "DISCIPLINE", value: "Computer Science + AI" },
      { label: "CURRENTLY", value: "Software Development Engineer" },
      { label: "LANGUAGES", value: "Python · C++ · TypeScript" },
      { label: "INTERESTS", value: "AI · ML · Backend · Research" },
    ],
  },

  about: {
    paragraphs: [
      `I am a Computer Science and Artificial Intelligence student with a deep fascination for how machines learn and reason. My work sits at the intersection of rigorous engineering and creative problem-solving.`,
      `Whether I am architecting distributed systems, training neural networks, or optimizing algorithms, I approach every challenge with the same principle: simplicity is the ultimate sophistication.`,
      `When not coding, you will find me exploring computational art, reading research papers, or contributing to open-source projects that push the boundaries of what software can do.`,
    ],
  },

  featuredProject: {
    name: "NeuralFlow",
    tagline: "Real-time ML Inference Platform",
    description: "A production-grade machine learning inference platform built with Python, FastAPI, and TensorRT. Processes 10,000+ predictions per second with sub-10ms latency. Features auto-scaling, A/B testing, and observability dashboards.",
    tech: ["Python", "FastAPI", "TensorRT", "Docker", "Kubernetes", "Prometheus"],
    github: "https://github.com/deepanshiruhil/neuralflow",
    live: "https://neuralflow.demo",
    highlights: [
      "10,000+ inferences/sec at <10ms latency",
      "Auto-scaling with custom Kubernetes operators",
      "Built-in model versioning and A/B testing",
    ],
  },

  projects: [
    {
      id: "neuralflow",
      name: "NeuralFlow",
      tagline: "Real-time ML Inference Platform",
      description: "Production-grade ML inference platform with auto-scaling and sub-10ms latency.",
      tech: ["Python", "FastAPI", "TensorRT", "Kubernetes"],
      github: "https://github.com/deepanshiruhil/neuralflow",
      live: "https://neuralflow.demo",
      category: "Backend / ML",
      year: "2024",
    },
    {
      id: "synapse",
      name: "SynapseDB",
      tagline: "Vector Database from Scratch",
      description: "A high-performance vector database implementing HNSW indexing and approximate nearest neighbor search.",
      tech: ["C++", "Rust", "gRPC", "Raft"],
      github: "https://github.com/deepanshiruhil/synapsedb",
      live: null,
      category: "Systems / Database",
      year: "2024",
    },
    {
      id: "cipher",
      name: "Cipher",
      tagline: "End-to-End Encrypted Notes",
      description: "Privacy-first note-taking application with zero-knowledge architecture and cross-device sync.",
      tech: ["TypeScript", "Next.js", "WebCrypto", "Prisma"],
      github: "https://github.com/deepanshiruhil/cipher",
      live: "https://cipher-notes.app",
      category: "Full Stack",
      year: "2023",
    },
    {
      id: "atlas",
      name: "Atlas Vision",
      tagline: "Autonomous Navigation System",
      description: "Computer vision pipeline for autonomous robot navigation using stereo depth estimation and SLAM.",
      tech: ["Python", "PyTorch", "OpenCV", "ROS2"],
      github: "https://github.com/deepanshiruhil/atlas-vision",
      live: null,
      category: "AI / Robotics",
      year: "2023",
    },
    {
      id: "zenith",
      name: "Zenith Compiler",
      tagline: "Educational Compiler for a Systems Language",
      description: "A complete compiler frontend and backend for a C-like systems language with LLVM IR generation.",
      tech: ["C++", "LLVM", "Flex", "Bison"],
      github: "https://github.com/deepanshiruhil/zenith",
      live: null,
      category: "Compilers",
      year: "2023",
    },
    {
      id: "flux",
      name: "Flux Graph",
      tagline: "Distributed Graph Processing Engine",
      description: "Distributed graph computation engine inspired by Pregel, capable of processing billion-edge graphs.",
      tech: ["Go", "gRPC", "BadgerDB", "Docker"],
      github: "https://github.com/deepanshiruhil/flux-graph",
      live: null,
      category: "Distributed Systems",
      year: "2022",
    },
  ],

  skills: {
    languages: [
      { name: "Python", level: 95 },
      { name: "C++", level: 88 },
      { name: "TypeScript", level: 85 },
      { name: "Go", level: 75 },
      { name: "Rust", level: 70 },
      { name: "SQL", level: 82 },
    ],
    frameworks: [
      { name: "PyTorch", level: 90 },
      { name: "FastAPI", level: 92 },
      { name: "TensorFlow", level: 80 },
      { name: "Next.js", level: 85 },
      { name: "Node.js", level: 78 },
      { name: "React", level: 82 },
    ],
    tools: [
      { name: "Docker & Kubernetes", level: 88 },
      { name: "Git & CI/CD", level: 90 },
      { name: "AWS / GCP", level: 80 },
      { name: "Linux", level: 92 },
      { name: "PostgreSQL", level: 85 },
      { name: "Redis", level: 78 },
    ],
    domains: [
      "Machine Learning",
      "Deep Learning",
      "Natural Language Processing",
      "Computer Vision",
      "Distributed Systems",
      "Backend Engineering",
      "System Design",
      "MLOps",
    ],
  },

  experience: [
    {
      year: "2024 — Present",
      role: "Software Development Engineer",
      company: "TechCorp AI",
      description: "Building production ML systems serving 1M+ daily users. Leading the inference optimization team, reducing model latency by 60% through quantization and TensorRT optimization.",
    },
    {
      year: "2023 — 2024",
      role: "ML Engineering Intern",
      company: "Research Labs",
      description: "Developed transformer-based models for document understanding. Published research on efficient attention mechanisms, achieving 40% reduction in compute without accuracy loss.",
    },
    {
      year: "2022 — 2023",
      role: "Backend Developer",
      company: "StartupXYZ",
      description: "Architected microservices handling 500K+ requests/day. Implemented event-driven architecture with Kafka, reducing system coupling and improving reliability.",
    },
  ],

  education: [
    {
      degree: "B.Tech in Computer Science & Artificial Intelligence",
      institution: "Indian Institute of Technology",
      year: "2021 — 2025",
      details: "CGPA: 9.2/10. Specialization in Machine Learning and Distributed Systems. Thesis on efficient transformer architectures for edge deployment.",
    },
    {
      degree: "Higher Secondary Education",
      institution: "Delhi Public School",
      year: "2019 — 2021",
      details: "PCM with Computer Science. Scored 98.2% in CBSE Board Examinations. National Olympiad qualifier in Informatics.",
    },
  ],

  achievements: [
    {
      title: "Google Summer of Code 2024",
      org: "Google",
      year: "2024",
      description: "Selected among 1,200 students globally. Contributed to TensorFlow Lite, implementing INT8 quantization optimizations for mobile deployment.",
    },
    {
      title: "ICPC Asia Regionals Finalist",
      org: "ICPC Foundation",
      year: "2023",
      description: "Ranked 12th in the Asia-West Continent Final. Solved 8/12 problems in the regional competition.",
    },
    {
      title: "Best Paper Award",
      org: "IEEE Conference on AI",
      year: "2023",
      description: "Awarded for research on 'Efficient Attention Mechanisms for Long Document Understanding' — 40% compute reduction with zero accuracy loss.",
    },
    {
      title: "Smart India Hackathon Winner",
      org: "Govt. of India",
      year: "2022",
      description: "National winner among 10,000+ teams. Built an AI-powered agricultural advisory system for rural farmers.",
    },
    {
      title: "AWS ML Specialty Certification",
      org: "Amazon Web Services",
      year: "2023",
      description: "Professional certification in machine learning on AWS. Expertise in SageMaker, EMR, and production ML pipelines.",
    },
    {
      title: "Gold Medalist — Mathematics Olympiad",
      org: "Homi Bhabha Centre",
      year: "2020",
      description: "National gold medal in the Indian National Mathematical Olympiad. Represented India at the Asian Pacific Mathematics Olympiad.",
    },
  ],

  creative: [
    { type: "writing", title: "The Geometry of Thought", category: "Essay" },
    { type: "art", title: "Neural Landscapes", category: "Generative Art" },
    { type: "photography", title: "Urban Symmetry", category: "Street" },
    { type: "writing", title: "On Simplicity", category: "Essay" },
    { type: "art", title: "Entropy", category: "Digital Illustration" },
    { type: "photography", title: "Light & Shadow", category: "Portrait" },
  ],
}
